### ISSUE TITLE
Issue while cloning the repo

### ISSUE THREAD

**Issue by notdanilo** [SamGinzburg/VectorVisor#3]
No idea why I am getting this error. Is remote corrupted?

```console
dangu@Desktop MINGW64 /d/dev/3rd
$ git clone https://github.com/SamGinzburg/VectorVisor/
Cloning into 'VectorVisor'...
remote: Enumerating objects: 10710, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 10710 (delta 63), reused 52 (delta 25), pack-reused 10591
Receiving objects: 100% (10710/10710), 220.62 MiB | 34.03 MiB/s, done.
Resolving deltas: 100% (7373/7373), done.
error: invalid path 'benchmarks/2022-12-18-02:01:45/a10g_cuda/gpu_cuda_bench_imageblur_bmp_0.txt'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by SamGinzburg** [comment]
Hi,

Thanks for checking out the project!

I think this is likely a OS/Filesystem issue on your end with the file paths. (No corruption AFAIK).
It looks like you may be trying to clone the repo on Windows which I think is the issue here (I see MINGW64 at the top).

Unfortunately because of some of the project deps, it will likely only compile/run on Linux (and somewhat on macOS) in the near future. You may have better luck trying to run using WSL2, although I'm not up-to-date with what the GPGPU/CUDA story there looks like (I seem to recall they added some GPGPU passthrough support but not 100% sure).

- Sam

**Comment by notdanilo** [comment]
Thanks for the info. I just tried to make it buildable on Windows, but I was facing new errors after fixing old errors. It was really time consuming. I unfortunately don't have Linux anywhere atm and idk if I will attempt the uncertainty of WSL2.
